# Generated by Django 4.2.20 on 2025-03-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='', max_length=100)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('url', models.TextField()),
                ('urlToImage', models.TextField()),
                ('publishedAt', models.DateTimeField()),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['publishedAt'],
            },
        ),
    ]
