# Generated by Django 4.2.20 on 2025-03-14 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='News',
        ),
    ]
