# Generated by Django 4.2.20 on 2025-03-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_news_description_alter_news_publishedat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.TextField(default=''),
        ),
    ]
